### ISSUE TITLE
Doesn't seem to render with newer version of JupyterLab

### ISSUE THREAD

**Issue by brentgunderson** [altair-viz/altair_data_server#44]
I recently upgraded JupyterLab, and I am assuming likely ipython and others as well, and charts with altair_data_server no longer seem to render.

```py
import altair as alt
import pandas as pd

source = pd.DataFrame(
    {
        "a": ["A", "B", "C", "D", "E", "F", "G", "H", "I"],
        "b": [28, 55, 43, 91, 81, 53, 19, 87, 52],
    }
)

alt.Chart(source).mark_bar().encode(x="a", y="b")  # Renders

alt.data_transformers.enable("data_server")
alt.Chart(source).mark_bar().encode(x="a", y="b") # does not render
```

Python version 3.8.6
Packages:
```
Package                   Version
------------------------- ----------
altair                    4.1.0
altair-data-server        0.4.1
ipykernel                 5.4.3
ipython                   7.19.0
ipython-genutils          0.2.0
jupyter-client            6.1.11
jupyter-core              4.7.0
jupyter-server            1.2.2
jupyterlab                3.0.5
jupyterlab-code-formatter 1.4.2
jupyterlab-pygments       0.1.2
jupyterlab-server         2.1.2
pandas                    1.2.0
```

![image](https://user-images.githubusercontent.com/42783590/105276078-3477f280-5b66-11eb-9f11-9d97f225364f.png)

**Comment by jakevdp** [comment]
Do you see any error in the browser console?

**Comment by brentgunderson** [comment]
Here's a grab of console

![image](https://user-images.githubusercontent.com/42783590/105366579-21483f80-5bc5-11eb-9b10-7b81e6d72702.png)

**Comment by jakevdp** [comment]
Thanks - the fix will be figuring out why the connection was refused.

**Comment by JamesSample** [comment]
I'm also experiencing this issue. My environment is a JupyterHub running on Kubernetes using Google Cloud platform (i.e. I'm running within a Docker container).

With Altair v3 I could use `alt.data_transformers.enable('json')` successfully, but since upgrading to Altair v4 I have only be able to use the `default` transformer that stores data within the notebook itself. I often plot medium to large datasets, so having the option to store data externally is really useful.

The following code works fine

```python
import altair as alt
from vega_datasets import data

source = data.cars()
alt.Chart(source).mark_circle(size=60).encode(
    x='Horsepower',
    y='Miles_per_Gallon',
    color='Origin',
    tooltip=['Name', 'Origin', 'Horsepower', 'Miles_per_Gallon']
).interactive()
```

But if I run the container locally (i.e. on `localhost`) and add `alt.data_transformers.enable('data_server')`, the output is blank and I see the following in the "inspect" console in Chrome:

```
GET http://localhost:15379/4d45d69bbd706eda330e96e79ad4bf46.json net::ERR_CONNECTION_REFUSED
WARN Loading failed http://localhost:15379/4d45d69bbd706eda330e96e79ad4bf46.json TypeError: Failed to fetch
    at Object.http (vega@5?noext:1:46069)
    at Object.Lo [as load] (vega@5?noext:1:45139)
    at async HT.request (vega@5?noext:1:60982)
    at async HT.preload (vega@5?noext:1:60831)
```

Altarnatively, if I deploy the container to my cloud-based JupyterHub and try adding `alt.data_transformers.enable('data_server_proxied', urlpath='/user-redirect')` (as in the documentation for [remote systems](https://github.com/altair-viz/altair_data_server#remote-systems)), I instead get `TypeError: __call__() got an unexpected keyword argument 'urlpath'`.

I'm using Altair 4.1.0, altair_data_server 0.4.1 and jupyter-server-proxy 3.2.1, all installed from conda-forge. 

If anyone has any tips for debugging I'd be grateful. Altair is my preferred plotting library for Python and it would be great to be able to use it again.

Thanks!

**Comment by joelostblom** [comment]
In Altair 5, the recommended way to work with large datasets is via Vegafusion. The documentation contains a section of [how to use the Vegafusion renderer in Altair](https://altair-viz.github.io/user_guide/large_datasets.html#vegafusion-data-transformer) and if you need additional performance you can [use the Vegafusion widget renderer](https://vegafusion.io/widget_renderer.html) instead. 

We are going to archive this repo, so I'm closing all the open issues and PRs before doing so. Try out the new options for working with large data mentioned above and if you run into issues, please open an issue directly in the altair or vegafusion repo.
